### PR TITLE
Allow access to Wayland sockets in subdirectories

### PR DESCRIPTION
**Pull request by robert-ancell**
This is the case for a confined server.

### CODE REVIEW

**Comment by robert-ancell** [comment]
I'm not 100% sure about the pattern (`/run/user/[0-9]*/{,*/}wayland-[0-9]*`), I don't know if you can do something like `/run/user/[0-9]*/**/wayland-[0-9]*` and if that is better.

**Comment by robert-ancell** [comment]
@jhenstridge please review.

**Comment by robert-ancell** [comment]
The journal message that suggests this is required is:
```
Jul 20 16:35:22 ubuntu audit[2826]: AVC apparmor="DENIED" operation="connect" profile="snap.gnome-characters.gnome-characters" name="/run/user/1001/snap.ubuntu-desktop-session/wayland-0" pid=2826 comm="org.gnome.Chara" requested_mask="wr" denied_mask="wr" fsuid=1001 ouid=1001
```

**Comment by jhenstridge** [comment]
This will need some more work before it'll be acceptable to merge to snapcore/snapd, but it'd be better to cover those in a PR against that repo.

In short, I think we'd want:

1. leave the existing constant as is
2. in AppArmorConnectedPlug, if `!implicitSystemConnectedSlot(slot)` add a second snippet granting access to `owner /run/user/[0-9]*/snap.%s/wayland-[0-9]*` substituting in slot.Snap().InstanceName().

That is, only grant access to the socket provided by the connected snap rather than all snaps.

**Pull request merged**
